version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tutor-connect
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - tutor-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tutor-network

volumes:
  mongodb_data:

networks:
  tutor-network:
    driver: bridge
