name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: cicd-env
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Docker image
        run: |
          docker build -t zupandit/tutor-connect:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push zupandit/tutor-connect:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: cicd-env
    steps:
    - name: SSH into EC2 and deploy container
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Pull the latest image from Docker Hub
          docker pull zupandit/tutor-connect:latest
          # Stop and remove any old container if it exists
          docker stop tutor-connect || true && docker rm tutor-connect || true
          # Run the container with environment variables passed via -e flags
          docker run -d --name tutor-connect -p 80:3000 \
            -e NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
            -e MONGODB_URI="mongodb://mongodb:27017/tutor-connect" \
            -e NEXTAUTH_URL="http://localhost:3000" \
            zupandit/tutor-connect:latest

