name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: cicd-env
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Docker image
        run: |
          docker build -t zupandit/tutor-connect:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push zupandit/tutor-connect:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: cicd-env
    steps:
      - name: SSH into EC2 and deploy container with docker run
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Ensure the custom network exists
            docker network ls | grep tutor-network || docker network create tutor-network

            # Start MongoDB container if not already running on the network
            if ! docker ps --filter "name=tutorconnect-mongodb" | grep tutorconnect-mongodb; then
              docker run -d --name tutorconnect-mongodb --network tutor-network -p 27017:27017 mongo:latest
            fi

            # Pull the latest image for the app
            docker pull zupandit/tutor-connect:latest

            # Stop and remove any existing app container
            docker stop tutor-connect || true && docker rm tutor-connect || true

            # Run the app container with environment variables hardcoded
            docker run -d --name tutor-connect -p 80:3000 --network tutor-network \
              -e NEXTAUTH_SECRET="uE6RdeaWKTJpHM+5ImRW+Tq6fzW8cRGtVUwbZGyrD4I=" \
              -e MONGODB_URI="mongodb://mongodb:27017/tutor-connect" \
              -e NEXTAUTH_URL="http://99.79.41.124" \
              zupandit/tutor-connect:latest

