name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: cicd-env
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Docker image
        run: |
          docker build -t zupandit/tutor-connect:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push zupandit/tutor-connect:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: cicd-env
    steps:
      - name: SSH into EC2 and deploy container with docker run
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Stop and remove existing containers
            docker stop tutor-connect tutorconnect-mongodb || true
            docker rm tutor-connect tutorconnect-mongodb || true

            # Remove existing network if it exists
            docker network rm tutor-network || true

            # Create a new network
            docker network create tutor-network

            # Start MongoDB container first
            docker run -d \
              --name tutorconnect-mongodb \
              --network tutor-network \
              -p 27017:27017 \
              mongo:latest

            # Wait for MongoDB to be ready
            sleep 5

            # Pull the latest image for the app
            docker pull zupandit/tutor-connect:latest

            # Run the app container
            docker run -d \
              --name tutor-connect \
              --network tutor-network \
              -p 80:3000 \
              -e NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
              -e MONGODB_URI="mongodb://tutorconnect-mongodb:27017/tutor-connect" \
              -e NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
              zupandit/tutor-connect:latest

            # Check container logs
            docker logs tutor-connect

